CREATE TABLE IF NOT EXISTS namespace (
    id INT(3) SIGNED PRIMARY KEY,
    name VARCHAR(64) DEFAULT NULL
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS page (
    id BIGINT UNSIGNED PRIMARY KEY,
    namespace INT(3) SIGNED DEFAULT NULL,
    search VARCHAR(255) DEFAULT NULL,
    redirect VARCHAR(255) DEFAULT NULL,
    title VARCHAR(255) DEFAULT NULL
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS contrib (
    id BIGINT UNSIGNED PRIMARY KEY,
    name VARCHAR(64) DEFAULT NULL
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS revision (
    id BIGINT UNSIGNED PRIMARY KEY,
    page BIGINT UNSIGNED DEFAULT NULL,
    contrib BIGINT UNSIGNED DEFAULT NULL,
    parent BIGINT UNSIGNED DEFAULT NULL,
    datetime DATETIME DEFAULT NULL,
    length INT DEFAULT NULL,
    minor BOOLEAN DEFAULT NULL,
    comment VARCHAR(255) DEFAULT NULL,
    sha1 VARCHAR(40) DEFAULT NULL,
    body LONGTEXT
) ENGINE=MyISAM;
